# Generated by Django 4.2 on 2023-04-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_reviews', models.TextField()),
                ('product_rate', models.FloatField()),
                ('product_availability', models.BooleanField()),
            ],
        ),
    ]
